before_script: "sudo apt-get install lua clang"
language: lua
script: "make test btest"

env:
  - CC=gcc BUILD=opt
  - CC=gcc BUILD=dbg
  - CC=clang BUILD=opt
  - CC=clang BUILD=dbg

branches:
  only:
      - master
